name: foo
favicon: null
layout_spectrum: 0.7431767375674099
typography_spectrum: 0.6003519834484905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.12554290262050927
purpose:
  - name: shares
    item: null
    url: null
